apiVersion: v1
kind: Service
metadata:
   labels:
     app: monitoring-prometheus
     component: prometheus
   name: monitoring-prometheus-nodeport
   namespace: kube-system
spec:
   ports:
   - name: http
     port: 9090
     protocol: TCP
     targetPort: 9090
   selector:
     app: monitoring-prometheus
     component: prometheus
   type: "NodePort"
