apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-elk-apps-name-ibm-icplogging-data-apps-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    path: /var/lib/appelk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.125.1.16
  persistentVolumeReclaimPolicy: Retain
  storageClassName: logging-storage-datanode
