apiVersion: monitoringcontroller.cloud.ibm.com/v1
kind: AlertRule
metadata:
  name: node-disk-pressure
spec:
  enabled: true
  data: |-
    groups:
      - name: ICPNodeDiskPressure
        rules:
          - alert: ICPNodeDiskPressure
            expr: kube_node_status_condition{condition="DiskPressure",status="true"} == 1
            labels:
              service: ICP
              severity: warning
            annotations:
              description: '{{ $labels.node }} is under disk pressure.'
              summary: Node is under disk pressure.
              type: Server
