apiVersion: monitoringcontroller.cloud.ibm.com/v1
kind: AlertRule
metadata:
  name: node-exporter-down
spec:
  enabled: true
  data: |-
    groups:
      - name: ICPNodeExporterDown
        rules:
          - alert: ICPNodeExporterDown
            expr: absent(up{component="nodeexporter"} == 1)
            for: 10m
            labels:
              severity: warning
            annotations:
              description: Prometheus could not scrape a node-exporter for more than 10m,
                or node-exporters have disappeared from discovery.
              summary: node-exporter cannot be scraped
              type: MonitoringTarget
