apiVersion: monitoringcontroller.cloud.ibm.com/v1
kind: AlertRule
metadata:
  name: prometheus-config-reload-failed
spec:
  enabled: true
  data: |-
    groups:
      - name: PrometheusConfigReloadFailed.rules
        rules:
          - alert: PrometheusConfigReloadFailed
            expr: prometheus_config_last_reload_successful == 0
            for: 10m
            labels:
              severity: warning
            annotations:
              description: Reloading Prometheus configuration has failed for {{ $labels.namespace
                }}/{{ $labels.pod}}.
              summary: Prometheus configuration reload has failed
              type: Prometheus
