apiVersion: monitoringcontroller.cloud.ibm.com/v1
kind: AlertRule
metadata:
  name: api-server-down
spec:
  enabled: true
  data: |-
    groups:
      - name: ICPApiserverDown
        rules:
          - alert: ICPApiserverDown
            expr: absent(up{job="kubernetes-apiservers"} == 1)
            for: 5m
            labels:
              severity: critical
            annotations:
              description: Prometheus failed to scrape API server(s), or all API servers have
                disappeared from service discovery.
              summary: API server unreachable

