apiVersion: monitoringcontroller.cloud.ibm.com/v1
kind: AlertRule
metadata:
  name: monitoring-target-down
spec:
  enabled: true
  data: |-
    groups:
      - name: ICPMonitoringTargetDown
        rules:
          - alert: ICPMonitoringTargetDown
            expr: 100 * (count by(job) (up == 0) / count by(job) (up)) > 10
            for: 10m
            labels:
              severity: warning
            annotations:
              description: '{{ $value }}% or more of {{ $labels.job }} targets are down.'
              summary: Targets are down
