apiVersion: monitoringcontroller.cloud.ibm.com/v1
kind: AlertRule
metadata:
  name: prometheus-error-sending-alerts
spec:
  enabled: true
  data: |-
    groups:
      - name: PrometheusErrorSendingAlerts.rules
        rules:
          - alert: PrometheusErrorSendingAlerts
           expr: rate(prometheus_notifications_errors_total[5m]) / rate(prometheus_notifications_sent_total[5m])
              > 0.01
            for: 10m
            labels:
              severity: warning
            annotations:
              description: Errors while sending alerts from Prometheus {{$labels.namespace}}/{{$labels.pod}}
                to Alertmanager {{$labels.Alertmanager}}
              summary: Errors while sending alert from Prometheus
