apiVersion: monitoringcontroller.cloud.ibm.com/v1
kind: AlertRule
metadata:
  name: prometheus-not-connected-to-alertmanagers
spec:
  enabled: true
  data: |-
    groups:
      - name: PrometheusNotConnectedToAlertmanagers.rules
        rules:
          - alert: PrometheusNotConnectedToAlertmanagers
            expr: prometheus_notifications_alertmanagers_discovered < 1
            for: 10m
            labels:
              severity: warning
            annotations:
              description: Prometheus {{ $labels.namespace }}/{{ $labels.pod}} is not connected
                to any Alertmanagers
              summary: Prometheus is not connected to any Alertmanagers
